"""initial schema

Revision ID: 4eed95d0ac63
Revises: 
Create Date: 2026-10-08 16:44:04.206577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eed95d0ac63'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('emp_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), server_default='user', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('emp_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_emp_id'), 'users', ['emp_id'], unique=False)
    op.create_index(op.f('ix_users_last_seen_at'), 'users', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('user_activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['users.emp_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activity_emp_id'), 'user_activity', ['emp_id'], unique=False)
    op.create_index(op.f('ix_user_activity_event_type'), 'user_activity', ['event_type'], unique=False)
    op.create_index(op.f('ix_user_activity_occurred_at'), 'user_activity', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_user_activity_token_hash'), 'user_activity', ['token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_activity_token_hash'), table_name='user_activity')
    op.drop_index(op.f('ix_user_activity_occurred_at'), table_name='user_activity')
    op.drop_index(op.f('ix_user_activity_event_type'), table_name='user_activity')
    op.drop_index(op.f('ix_user_activity_emp_id'), table_name='user_activity')
    op.drop_table('user_activity')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_last_seen_at'), table_name='users')
    op.drop_index(op.f('ix_users_emp_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
